### ISSUE TITLE
Hitting back on a lesson removed the X

### ISSUE THREAD

**Issue by AustinSumigray** [esnaultdev/BunPyro#7] opened 2021-05-16 16:12 UTC
During the first review of a series I typed in the wrong answer. When I hit X it seemed to work, but the icon disappeared. Afterwards, the review was still marked incorrect.
![Screenshot_20210516-120951_BunPyro](https://user-images.githubusercontent.com/8961217/118404217-ee2c2f00-b63f-11eb-9616-d9b5713909dd.jpg)

**Comment by esnaultdev** [comment] 2021-05-17 15:56
Thanks for the report!

> When I hit X it seemed to work, but the icon disappeared.

Currently, the icon is only shown when an incorrect answer can be ignored. So it's normal for it to disappear when clicked.
However, having this ripple get stuck is not normal. It seems to be a bug of the material components library, I will see if I can work around it while waiting for an upstream fix.

> Afterwards, the review was still marked incorrect.

I could reproduce this. It seems that it's successfully ignored, but the summary is wrong. I will fix this right away.

**Comment by esnaultdev** [comment] 2021-05-17 16:46
Summary fixed in 9ecad07c336b9380ce230e750b34f9cae3abec41.
I've made an ugly workaround for the ripple in bdff7585c808b932e759e4b25c26676598d23b58.

I think that you're building the project from Github, @AustinSumigray, right?
Or should I publish a new update on Firebase App Distribution if that's more convenient for you?

**Comment by AustinSumigray** [comment] 2021-05-17 18:16
Building is kind of a pain, but I could keep doing so if you like. I had
switched to Firebase.

**Comment by esnaultdev** [comment] 2021-05-18 15:01
Understood :ok_hand: I've just published 0.4.0-alpha03 which includes the fixes mentioned above.

**Closed as completed by esnaultdev** 2021-05-18 15:01 UTC
